// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AdminPrivilegesInitParameters struct {

	// (Boolean) Enables a project admin to define the resources to be indexed by Xray
	// Enables a project admin to define the resources to be indexed by Xray
	IndexResources *bool `json:"indexResources,omitempty" tf:"index_resources,omitempty"`

	// (Boolean) Allows the Project Admin to manage Platform users/groups as project members with different roles.
	// Allows the Project Admin to manage Platform users/groups as project members with different roles.
	ManageMembers *bool `json:"manageMembers,omitempty" tf:"manage_members,omitempty"`

	// (Boolean) Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	// Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	ManageRemoteRepository *bool `json:"manageRemoteRepository,omitempty" tf:"manage_remote_repository,omitempty"`

	// repositories, builds and Pipelines resources on the project level.
	// Allows the Project Admin to manage resources - repositories, builds and Pipelines resources on the project level.
	ManageResources *bool `json:"manageResources,omitempty" tf:"manage_resources,omitempty"`
}

type AdminPrivilegesObservation struct {

	// (Boolean) Enables a project admin to define the resources to be indexed by Xray
	// Enables a project admin to define the resources to be indexed by Xray
	IndexResources *bool `json:"indexResources,omitempty" tf:"index_resources,omitempty"`

	// (Boolean) Allows the Project Admin to manage Platform users/groups as project members with different roles.
	// Allows the Project Admin to manage Platform users/groups as project members with different roles.
	ManageMembers *bool `json:"manageMembers,omitempty" tf:"manage_members,omitempty"`

	// (Boolean) Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	// Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	ManageRemoteRepository *bool `json:"manageRemoteRepository,omitempty" tf:"manage_remote_repository,omitempty"`

	// repositories, builds and Pipelines resources on the project level.
	// Allows the Project Admin to manage resources - repositories, builds and Pipelines resources on the project level.
	ManageResources *bool `json:"manageResources,omitempty" tf:"manage_resources,omitempty"`
}

type AdminPrivilegesParameters struct {

	// (Boolean) Enables a project admin to define the resources to be indexed by Xray
	// Enables a project admin to define the resources to be indexed by Xray
	// +kubebuilder:validation:Optional
	IndexResources *bool `json:"indexResources" tf:"index_resources,omitempty"`

	// (Boolean) Allows the Project Admin to manage Platform users/groups as project members with different roles.
	// Allows the Project Admin to manage Platform users/groups as project members with different roles.
	// +kubebuilder:validation:Optional
	ManageMembers *bool `json:"manageMembers" tf:"manage_members,omitempty"`

	// (Boolean) Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	// Allows the Project Admin to create and manage remote repositories. Requires manage_resources to be enabled. Available in Artifactory 7.134 and later.
	// +kubebuilder:validation:Optional
	ManageRemoteRepository *bool `json:"manageRemoteRepository,omitempty" tf:"manage_remote_repository,omitempty"`

	// repositories, builds and Pipelines resources on the project level.
	// Allows the Project Admin to manage resources - repositories, builds and Pipelines resources on the project level.
	// +kubebuilder:validation:Optional
	ManageResources *bool `json:"manageResources" tf:"manage_resources,omitempty"`
}

type GroupInitParameters struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type GroupObservation struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type GroupParameters struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory group
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles" tf:"roles,omitempty"`
}

type MemberInitParameters struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type MemberObservation struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type MemberParameters struct {

	// (String) Must be existing Artifactory group
	// Must be existing Artifactory user
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// defined Project or custom roles
	// List of pre-defined Project or custom roles
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles" tf:"roles,omitempty"`
}

type ProjectInitParameters struct {

	// (Block Set) (see below for nested schema)
	AdminPrivileges []AdminPrivilegesInitParameters `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// (Boolean) Block deployment of artifacts if storage quota is exceeded.
	// Block deployment of artifacts if storage quota is exceeded.
	//
	// ~>This setting only applies to self-hosted environment. See [Manage Storage Quotas](https://jfrog.com/help/r/jfrog-platform-administration-documentation/manage-storage-quotas).
	BlockDeploymentsOnLimit *bool `json:"blockDeploymentsOnLimit,omitempty" tf:"block_deployments_on_limit,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Also known as project name on the UI
	// Also known as project name on the UI
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	// Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	EmailNotification *bool `json:"emailNotification,omitempty" tf:"email_notification,omitempty"`

	// (Block Set, Deprecated) Project group. Element has one to one mapping with the JFrog Project Groups API (see below for nested schema)
	// Project group. Element has one to one mapping with the [JFrog Project Groups API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateGroupinProject)
	Group []GroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	// 1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	// Storage quota in GiB. Must be 1 or larger. Set to -1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	MaxStorageInGibibytes *float64 `json:"maxStorageInGibibytes,omitempty" tf:"max_storage_in_gibibytes,omitempty"`

	// (Block Set, Deprecated) Member of the project. Element has one to one mapping with the JFrog Project Users API. (see below for nested schema)
	// Member of the project. Element has one to one mapping with the [JFrog Project Users API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateUserinProject).
	Member []MemberInitParameters `json:"member,omitempty" tf:"member,omitempty"`

	// (Set of String, Deprecated)  List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting project_key attribute in each artifactory_*_repository resource in the artifactory provider, you will need to use lifecycle.ignore_changes in the project resource to avoid state drift.
	// (Optional) List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting `project_key` attribute in each `artifactory_*_repository` resource in the `artifactory` provider, you will need to use `lifecycle.ignore_changes` in the `project` resource to avoid state drift.
	//
	// ```hcl
	// lifecycle {
	// ignore_changes = [
	// repos
	// ]
	// }
	// ```
	// +listType=set
	Repos []*string `json:"repos,omitempty" tf:"repos,omitempty"`

	// (Block Set, Deprecated) Project role. Element has one to one mapping with the JFrog Project Roles API (see below for nested schema)
	// Project role. Element has one to one mapping with the [JFrog Project Roles API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AddaNewRole)
	Role []RoleInitParameters `json:"role,omitempty" tf:"role,omitempty"`

	// (Boolean) When set to true, this resource will ignore the group attributes and allow users to be managed by project_group resource instead. Default to true.
	// When set to true, this resource will ignore the `group` attributes and allow users to be managed by `project_group` resource instead. Default to `true`.
	UseProjectGroupResource *bool `json:"useProjectGroupResource,omitempty" tf:"use_project_group_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the repos attributes and allow repository to be managed by project_repository resource instead. Default to true.
	// When set to true, this resource will ignore the `repos` attributes and allow repository to be managed by `project_repository` resource instead. Default to `true`.
	UseProjectRepositoryResource *bool `json:"useProjectRepositoryResource,omitempty" tf:"use_project_repository_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the roles attributes and allow roles to be managed by project_role resource instead. Default to true.
	// When set to true, this resource will ignore the `roles` attributes and allow roles to be managed by `project_role` resource instead. Default to `true`.
	UseProjectRoleResource *bool `json:"useProjectRoleResource,omitempty" tf:"use_project_role_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the member attributes and allow users to be managed by project_user resource instead. Default to true.
	// When set to true, this resource will ignore the `member` attributes and allow users to be managed by `project_user` resource instead. Default to `true`.
	UseProjectUserResource *bool `json:"useProjectUserResource,omitempty" tf:"use_project_user_resource,omitempty"`
}

type ProjectObservation struct {

	// (Block Set) (see below for nested schema)
	AdminPrivileges []AdminPrivilegesObservation `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// (Boolean) Block deployment of artifacts if storage quota is exceeded.
	// Block deployment of artifacts if storage quota is exceeded.
	//
	// ~>This setting only applies to self-hosted environment. See [Manage Storage Quotas](https://jfrog.com/help/r/jfrog-platform-administration-documentation/manage-storage-quotas).
	BlockDeploymentsOnLimit *bool `json:"blockDeploymentsOnLimit,omitempty" tf:"block_deployments_on_limit,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Also known as project name on the UI
	// Also known as project name on the UI
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	// Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	EmailNotification *bool `json:"emailNotification,omitempty" tf:"email_notification,omitempty"`

	// (Block Set, Deprecated) Project group. Element has one to one mapping with the JFrog Project Groups API (see below for nested schema)
	// Project group. Element has one to one mapping with the [JFrog Project Groups API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateGroupinProject)
	Group []GroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	// Storage quota in GiB. Must be 1 or larger. Set to -1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	MaxStorageInGibibytes *float64 `json:"maxStorageInGibibytes,omitempty" tf:"max_storage_in_gibibytes,omitempty"`

	// (Block Set, Deprecated) Member of the project. Element has one to one mapping with the JFrog Project Users API. (see below for nested schema)
	// Member of the project. Element has one to one mapping with the [JFrog Project Users API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateUserinProject).
	Member []MemberObservation `json:"member,omitempty" tf:"member,omitempty"`

	// (Set of String, Deprecated)  List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting project_key attribute in each artifactory_*_repository resource in the artifactory provider, you will need to use lifecycle.ignore_changes in the project resource to avoid state drift.
	// (Optional) List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting `project_key` attribute in each `artifactory_*_repository` resource in the `artifactory` provider, you will need to use `lifecycle.ignore_changes` in the `project` resource to avoid state drift.
	//
	// ```hcl
	// lifecycle {
	// ignore_changes = [
	// repos
	// ]
	// }
	// ```
	// +listType=set
	Repos []*string `json:"repos,omitempty" tf:"repos,omitempty"`

	// (Block Set, Deprecated) Project role. Element has one to one mapping with the JFrog Project Roles API (see below for nested schema)
	// Project role. Element has one to one mapping with the [JFrog Project Roles API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AddaNewRole)
	Role []RoleObservation `json:"role,omitempty" tf:"role,omitempty"`

	// (Boolean) When set to true, this resource will ignore the group attributes and allow users to be managed by project_group resource instead. Default to true.
	// When set to true, this resource will ignore the `group` attributes and allow users to be managed by `project_group` resource instead. Default to `true`.
	UseProjectGroupResource *bool `json:"useProjectGroupResource,omitempty" tf:"use_project_group_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the repos attributes and allow repository to be managed by project_repository resource instead. Default to true.
	// When set to true, this resource will ignore the `repos` attributes and allow repository to be managed by `project_repository` resource instead. Default to `true`.
	UseProjectRepositoryResource *bool `json:"useProjectRepositoryResource,omitempty" tf:"use_project_repository_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the roles attributes and allow roles to be managed by project_role resource instead. Default to true.
	// When set to true, this resource will ignore the `roles` attributes and allow roles to be managed by `project_role` resource instead. Default to `true`.
	UseProjectRoleResource *bool `json:"useProjectRoleResource,omitempty" tf:"use_project_role_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the member attributes and allow users to be managed by project_user resource instead. Default to true.
	// When set to true, this resource will ignore the `member` attributes and allow users to be managed by `project_user` resource instead. Default to `true`.
	UseProjectUserResource *bool `json:"useProjectUserResource,omitempty" tf:"use_project_user_resource,omitempty"`
}

type ProjectParameters struct {

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AdminPrivileges []AdminPrivilegesParameters `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// (Boolean) Block deployment of artifacts if storage quota is exceeded.
	// Block deployment of artifacts if storage quota is exceeded.
	//
	// ~>This setting only applies to self-hosted environment. See [Manage Storage Quotas](https://jfrog.com/help/r/jfrog-platform-administration-documentation/manage-storage-quotas).
	// +kubebuilder:validation:Optional
	BlockDeploymentsOnLimit *bool `json:"blockDeploymentsOnLimit,omitempty" tf:"block_deployments_on_limit,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Also known as project name on the UI
	// Also known as project name on the UI
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	// Alerts will be sent when reaching 75% and 95% of the storage quota. This serves as a notification only and is not a blocker
	// +kubebuilder:validation:Optional
	EmailNotification *bool `json:"emailNotification,omitempty" tf:"email_notification,omitempty"`

	// (Block Set, Deprecated) Project group. Element has one to one mapping with the JFrog Project Groups API (see below for nested schema)
	// Project group. Element has one to one mapping with the [JFrog Project Groups API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateGroupinProject)
	// +kubebuilder:validation:Optional
	Group []GroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// 1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	// Storage quota in GiB. Must be 1 or larger. Set to -1 for unlimited storage. This is translated to binary bytes for Artifactory API. So for a 1TB quota, this should be set to 1024 (vs 1000) which will translate to 1099511627776 bytes for the API.
	// +kubebuilder:validation:Optional
	MaxStorageInGibibytes *float64 `json:"maxStorageInGibibytes,omitempty" tf:"max_storage_in_gibibytes,omitempty"`

	// (Block Set, Deprecated) Member of the project. Element has one to one mapping with the JFrog Project Users API. (see below for nested schema)
	// Member of the project. Element has one to one mapping with the [JFrog Project Users API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateUserinProject).
	// +kubebuilder:validation:Optional
	Member []MemberParameters `json:"member,omitempty" tf:"member,omitempty"`

	// (Set of String, Deprecated)  List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting project_key attribute in each artifactory_*_repository resource in the artifactory provider, you will need to use lifecycle.ignore_changes in the project resource to avoid state drift.
	// (Optional) List of existing repo keys to be assigned to the project. If you wish to use the alternate method of setting `project_key` attribute in each `artifactory_*_repository` resource in the `artifactory` provider, you will need to use `lifecycle.ignore_changes` in the `project` resource to avoid state drift.
	//
	// ```hcl
	// lifecycle {
	// ignore_changes = [
	// repos
	// ]
	// }
	// ```
	// +kubebuilder:validation:Optional
	// +listType=set
	Repos []*string `json:"repos,omitempty" tf:"repos,omitempty"`

	// (Block Set, Deprecated) Project role. Element has one to one mapping with the JFrog Project Roles API (see below for nested schema)
	// Project role. Element has one to one mapping with the [JFrog Project Roles API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AddaNewRole)
	// +kubebuilder:validation:Optional
	Role []RoleParameters `json:"role,omitempty" tf:"role,omitempty"`

	// (Boolean) When set to true, this resource will ignore the group attributes and allow users to be managed by project_group resource instead. Default to true.
	// When set to true, this resource will ignore the `group` attributes and allow users to be managed by `project_group` resource instead. Default to `true`.
	// +kubebuilder:validation:Optional
	UseProjectGroupResource *bool `json:"useProjectGroupResource,omitempty" tf:"use_project_group_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the repos attributes and allow repository to be managed by project_repository resource instead. Default to true.
	// When set to true, this resource will ignore the `repos` attributes and allow repository to be managed by `project_repository` resource instead. Default to `true`.
	// +kubebuilder:validation:Optional
	UseProjectRepositoryResource *bool `json:"useProjectRepositoryResource,omitempty" tf:"use_project_repository_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the roles attributes and allow roles to be managed by project_role resource instead. Default to true.
	// When set to true, this resource will ignore the `roles` attributes and allow roles to be managed by `project_role` resource instead. Default to `true`.
	// +kubebuilder:validation:Optional
	UseProjectRoleResource *bool `json:"useProjectRoleResource,omitempty" tf:"use_project_role_resource,omitempty"`

	// (Boolean) When set to true, this resource will ignore the member attributes and allow users to be managed by project_user resource instead. Default to true.
	// When set to true, this resource will ignore the `member` attributes and allow users to be managed by `project_user` resource instead. Default to `true`.
	// +kubebuilder:validation:Optional
	UseProjectUserResource *bool `json:"useProjectUserResource,omitempty" tf:"use_project_user_resource,omitempty"`
}

type RoleInitParameters struct {

	// defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// List of pre-defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// defined environments (DEV, PROD)
	// A repository can be available in different environments. Members with roles defined in the set environment will have access to the repository. List of pre-defined environments (DEV, PROD)
	// +listType=set
	Environments []*string `json:"environments,omitempty" tf:"environments,omitempty"`

	// (String) Must be existing Artifactory group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Type of role. Only "CUSTOM" is supported
	// Type of role. Only "CUSTOM" is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RoleObservation struct {

	// defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// List of pre-defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// defined environments (DEV, PROD)
	// A repository can be available in different environments. Members with roles defined in the set environment will have access to the repository. List of pre-defined environments (DEV, PROD)
	// +listType=set
	Environments []*string `json:"environments,omitempty" tf:"environments,omitempty"`

	// (String) Must be existing Artifactory group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Type of role. Only "CUSTOM" is supported
	// Type of role. Only "CUSTOM" is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RoleParameters struct {

	// defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// List of pre-defined actions (READ_REPOSITORY, ANNOTATE_REPOSITORY, DEPLOY_CACHE_REPOSITORY, DELETE_OVERWRITE_REPOSITORY, MANAGE_XRAY_MD_REPOSITORY, READ_RELEASE_BUNDLE, ANNOTATE_RELEASE_BUNDLE, CREATE_RELEASE_BUNDLE, DISTRIBUTE_RELEASE_BUNDLE, DELETE_RELEASE_BUNDLE, MANAGE_XRAY_MD_RELEASE_BUNDLE, READ_BUILD, ANNOTATE_BUILD, DEPLOY_BUILD, DELETE_BUILD, MANAGE_XRAY_MD_BUILD, READ_SOURCES_PIPELINE, TRIGGER_PIPELINE, READ_INTEGRATIONS_PIPELINE, READ_POOLS_PIPELINE, MANAGE_INTEGRATIONS_PIPELINE, MANAGE_SOURCES_PIPELINE, MANAGE_POOLS_PIPELINE, TRIGGER_SECURITY, ISSUES_SECURITY, LICENCES_SECURITY, REPORTS_SECURITY, WATCHES_SECURITY, POLICIES_SECURITY, RULES_SECURITY, MANAGE_MEMBERS, MANAGE_RESOURCES)
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// defined environments (DEV, PROD)
	// A repository can be available in different environments. Members with roles defined in the set environment will have access to the repository. List of pre-defined environments (DEV, PROD)
	// +kubebuilder:validation:Optional
	// +listType=set
	Environments []*string `json:"environments" tf:"environments,omitempty"`

	// (String) Must be existing Artifactory group
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) Type of role. Only "CUSTOM" is supported
	// Type of role. Only "CUSTOM" is supported
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. Provides an Artifactory project resource. This can be used to create and manage Artifactory project, maintain users/groups/roles/repos. Repository Configuration After the project configuration is applied with repos attribute set, the repository's attributes project_key and project_environments would be updated with the project's data. To avoid this, apply lifecycle.ignore_changes:
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,jfrog-project}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
