apiVersion: project.jfrog.com/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: myenv
  name: myenv
spec:
  forProvider:
    projectKey: myproj
