apiVersion: project.jfrog.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: myproject
  name: myproject
spec:
  forProvider:
    adminPrivileges:
    - indexResources: true
      manageMembers: true
      manageRemoteRepository: true
      manageResources: true
    blockDeploymentsOnLimit: false
    description: My Project
    displayName: My Project
    emailNotification: true
    maxStorageInGibibytes: 10
