apiVersion: project.jfrog.com/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: myprojectrepo
  name: myprojectrepo
spec:
  forProvider:
    projectKey: myproj
