apiVersion: project.jfrog.com/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/user
  labels:
    testing.upbound.io/example-name: myuser
  name: myuser
spec:
  forProvider:
    projectKey: myproj
    roles:
    - Viewer
