apiVersion: project.m.jfrog.com/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/role
  labels:
    testing.upbound.io/example-name: myrole
  name: myrole
  namespace: crossplane-system
spec:
  forProvider:
    actions:
    - READ_REPOSITORY
    - ANNOTATE_REPOSITORY
    environments:
    - DEV
    projectKey: ${project.myproject.key}
    type: CUSTOM
