// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ShareRepositoryInitParameters struct {

	// Only mode to avoid any changes or modifications of the shared content.
	// Share repository with a Project in Read-Only mode to avoid any changes or modifications of the shared content.
	//
	// ->Only available for Artifactory 7.94.0 or later.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`
}

type ShareRepositoryObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Only mode to avoid any changes or modifications of the shared content.
	// Share repository with a Project in Read-Only mode to avoid any changes or modifications of the shared content.
	//
	// ->Only available for Artifactory 7.94.0 or later.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) The project key to which the repository should be shared with.
	// The project key to which the repository should be shared with.
	TargetProjectKey *string `json:"targetProjectKey,omitempty" tf:"target_project_key,omitempty"`
}

type ShareRepositoryParameters struct {

	// Only mode to avoid any changes or modifications of the shared content.
	// Share repository with a Project in Read-Only mode to avoid any changes or modifications of the shared content.
	//
	// ->Only available for Artifactory 7.94.0 or later.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) The project key to which the repository should be shared with.
	// The project key to which the repository should be shared with.
	// +kubebuilder:validation:Required
	TargetProjectKey *string `json:"targetProjectKey" tf:"target_project_key,omitempty"`
}

// ShareRepositorySpec defines the desired state of ShareRepository
type ShareRepositorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ShareRepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ShareRepositoryInitParameters `json:"initProvider,omitempty"`
}

// ShareRepositoryStatus defines the observed state of ShareRepository.
type ShareRepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ShareRepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ShareRepository is the Schema for the ShareRepositorys API. Share a local or remote repository with a list of projects. Project Members of the target project are granted actions to the shared repository according to their Roles and Role actions assigned in the target Project. Requires a user assigned with the 'Administer the Platform' role. ->Only available for Artifactory 7.90.1 or later.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,jfrogproject}
type ShareRepository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ShareRepositorySpec   `json:"spec"`
	Status            ShareRepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ShareRepositoryList contains a list of ShareRepositorys
type ShareRepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ShareRepository `json:"items"`
}

// Repository type metadata.
var (
	ShareRepository_Kind             = "ShareRepository"
	ShareRepository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ShareRepository_Kind}.String()
	ShareRepository_KindAPIVersion   = ShareRepository_Kind + "." + CRDGroupVersion.String()
	ShareRepository_GroupVersionKind = CRDGroupVersion.WithKind(ShareRepository_Kind)
)

func init() {
	SchemeBuilder.Register(&ShareRepository{}, &ShareRepositoryList{})
}
