name: Publish Provider Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string to use while publishing the package (e.g. v1.0.0-alpha.1)"
        default: ''
        required: false
      go-version:
        description: 'Go version to use if building needs to be done'
        default: '1.24'
        required: false

jobs:
  # publish-provider-package:
  #   uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@451c4dc6ad3691b0a702a997a0ac24e8bbc8bbaa # main
  #   with:
  #     repository: provider-jfrog-project
  #     version: ${{ github.event.inputs.version }}
  #     go-version: ${{ github.event.inputs.go-version }}
  #     cleanup-disk: true
  #   secrets:
  #     GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
  #     XPKG_MIRROR_TOKEN: ${{ secrets.XPKG_MIRROR_TOKEN }}
  #     XPKG_MIRROR_ACCESS_ID: ${{ secrets.XPKG_MIRROR_ACCESS_ID }}

  publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ github.event.inputs.go-version || '1.24' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install crossplane CLI
        run: |
          curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | sh
          sudo mv crossplane /usr/local/bin/

      - name: Build provider binaries
        run: make build VERSION=${{ github.event.inputs.version }} PLATFORMS="linux_amd64 linux_arm64"

      - name: Build xpkg
        run: make xpkg.build VERSION=${{ github.event.inputs.version }} XPKG_REG_ORGS=ghcr.io/mikegio27 PLATFORMS="linux_amd64 linux_arm64"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push xpkg
        run: make publish.artifacts VERSION=${{ github.event.inputs.version }} XPKG_REG_ORGS=ghcr.io/mikegio27 PLATFORMS="linux_amd64 linux_arm64"
